
ma · SQL
-- ==========================================================
-- 新思想论坛 / NT论坛 — 完整数据库结构 (Schema) 与权限策略 (RLS)
-- 执行位置: Supabase 后台 -> SQL Editor -> 整段粘贴运行
-- 说明: 这一版补全了原脚本缺失的 notifications / collections 表，
--       补全了 profiles.age / profiles.bio 字段，
--       并修复了 notifications 表完全没有 RLS 策略导致的安全漏洞。
-- ==========================================================
 
-- 1. 核心表
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  age int,
  bio text,
  role text default 'user', -- user(普通) / admin(管理员)
  created_at timestamp with time zone default now()
);
 
create table if not exists posts (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid references auth.users on delete cascade not null,
  status text default 'pending', -- pending(待审) / approved(公开) / banned(封禁)
  created_at timestamp with time zone default now()
);
 
create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts on delete cascade not null,
  user_id uuid references auth.users on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default now()
);
 
-- 全站通知（之前的脚本里完全缺失，但前端已经在用）
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  content text not null,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);
 
-- 收藏（之前的脚本里完全缺失，但前端已经在用）
create table if not exists collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  post_id bigint references posts on delete cascade not null,
  created_at timestamp with time zone default now(),
  unique (user_id, post_id)
);
 
-- 2. 开启行级安全 (RLS)
alter table profiles enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;
alter table notifications enable row level security;
alter table collections enable row level security;
 
-- 3. 配置安全策略
do $$
begin
  -- ---------- profiles ----------
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Public profiles are viewable by everyone') then
    create policy "Public profiles are viewable by everyone" on profiles for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile" on profiles for update
      using ( auth.uid() = id )
      with check ( auth.uid() = id and role = 'user' ); -- 普通用户不能把自己升级成 admin
  end if;
 
  -- ---------- posts ----------
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Authenticated users can create posts') then
    create policy "Authenticated users can create posts" on posts for insert to authenticated
      with check ( auth.uid() = user_id );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Approved posts or own posts are viewable') then
    create policy "Approved posts or own posts are viewable" on posts for select
      using ( status = 'approved' or auth.uid() = user_id or auth.uid() in (select id from profiles where role = 'admin') );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Admins can update any post') then
    create policy "Admins can update any post" on posts for update
      using ( auth.uid() in (select id from profiles where role = 'admin') )
      with check ( auth.uid() in (select id from profiles where role = 'admin') );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Users can delete own posts') then
    create policy "Users can delete own posts" on posts for delete using ( auth.uid() = user_id );
  end if;
 
  -- ---------- comments ----------
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Comments are viewable by everyone') then
    create policy "Comments are viewable by everyone" on comments for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Authenticated users can create comments') then
    create policy "Authenticated users can create comments" on comments for insert to authenticated
      with check ( auth.uid() = user_id );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Users can delete own comments') then
    create policy "Users can delete own comments" on comments for delete using ( auth.uid() = user_id );
  end if;
 
  -- ---------- notifications (之前完全没有策略，存在漏洞，这里补全) ----------
  if not exists (select 1 from pg_policies where tablename = 'notifications' and policyname = 'Active notifications are viewable by everyone') then
    create policy "Active notifications are viewable by everyone" on notifications for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'notifications' and policyname = 'Only admins can insert notifications') then
    create policy "Only admins can insert notifications" on notifications for insert to authenticated
      with check ( auth.uid() in (select id from profiles where role = 'admin') );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'notifications' and policyname = 'Only admins can update notifications') then
    create policy "Only admins can update notifications" on notifications for update
      using ( auth.uid() in (select id from profiles where role = 'admin') )
      with check ( auth.uid() in (select id from profiles where role = 'admin') );
  end if;
 
  -- ---------- collections ----------
  if not exists (select 1 from pg_policies where tablename = 'collections' and policyname = 'Users can view own collections') then
    create policy "Users can view own collections" on collections for select using ( auth.uid() = user_id );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'collections' and policyname = 'Users can add own collections') then
    create policy "Users can add own collections" on collections for insert to authenticated
      with check ( auth.uid() = user_id );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'collections' and policyname = 'Users can delete own collections') then
    create policy "Users can delete own collections" on collections for delete using ( auth.uid() = user_id );
  end if;
end $$;
 
-- 4. 触发器：注册后自动生成 profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;
 
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
 
-- ==========================================================
-- 5. 如何把某个账号设为管理员（手动执行一次即可，把邮箱换成你自己的）：
--
--   update profiles set role = 'admin' where id = (
--     select id from auth.users where email = 'your-email@example.com'
--   );
--
-- 重要：网站的“管理者模式密码输入框”只是前端 UI 的一道门，
-- 真正决定一个账号能否执行管理员操作（发通知、审核/封禁文章）
-- 的，是这里的 profiles.role = 'admin'。必须在数据库里手动设置，
-- 光知道前端密码是没用的——这就是为什么要用 RLS 而不是前端校验。
-- ==========================================================
 
