-- 1. 创建用户资料表
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  role text default 'user',
  created_at timestamp with time zone default now()
);

-- 2. 创建帖子表 (优化你的原表)
create table if not exists posts (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid references auth.users not null,
  status text default 'pending',
  created_at timestamp with time zone default now()
);

-- 3. 创建评论表
create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts on delete cascade not null,
  user_id uuid references auth.users not null,
  content text not null,
  created_at timestamp with time zone default now()
);

-- 4. 开启行级安全
alter table profiles enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;

-- 5. 配置策略 (跳过已存在策略报错)
do $$
begin
  -- Profiles 策略
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Public profiles are viewable by everyone') then
    create policy "Public profiles are viewable by everyone" on profiles for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );
  end if;

  -- Posts 策略
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Authenticated users can create posts') then
    create policy "Authenticated users can create posts" on posts for insert to authenticated with check ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Posts are viewable by everyone') then
    create policy "Posts are viewable by everyone" on posts for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Admins can update any post') then
    create policy "Admins can update any post" on posts for update using ( auth.uid() in (select id from profiles where role = 'admin') ) with check ( auth.uid() in (select id from profiles where role = 'admin') );
  end if;

  -- Comments 策略
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Comments are viewable by everyone') then
    create policy "Comments are viewable by everyone" on comments for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Authenticated users can create comments') then
    create policy "Authenticated users can create comments" on comments for insert to authenticated with check ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Users can delete own comments') then
    create policy "Users can delete own comments" on comments for delete using ( auth.uid() = user_id );
  end if;
end $$;

-- 6. 触发器（自动创建用户资料）
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
