-- ==========================================================
-- 论坛系统完整数据库结构 (Schema) 与权限策略 (RLS)
-- 执行位置: Supabase 后台 -> SQL Editor
-- ==========================================================

-- 1. 创建核心表 (用户资料、帖子、评论)
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  role text default 'user', -- 角色：user(普通), admin(管理员)
  created_at timestamp with time zone default now()
);

create table if not exists posts (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid references auth.users not null,
  status text default 'pending', -- pending(待审), approved(公开), banned(封禁)
  created_at timestamp with time zone default now()
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts on delete cascade not null,
  user_id uuid references auth.users not null,
  content text not null,
  created_at timestamp with time zone default now()
);

-- 2. 开启行级安全 (RLS)
alter table profiles enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;

-- 3. 配置安全策略 (防止未授权篡改)
do $$
begin
  -- 用户资料策略
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Public profiles are viewable by everyone') then
    create policy "Public profiles are viewable by everyone" on profiles for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'profiles' and policyname = 'Users can update own profile') then
    create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );
  end if;

  -- 帖子策略
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Authenticated users can create posts') then
    create policy "Authenticated users can create posts" on posts for insert to authenticated with check ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Posts are viewable by everyone') then
    create policy "Posts are viewable by everyone" on posts for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'posts' and policyname = 'Admins can update any post') then
    create policy "Admins can update any post" on posts for update 
    using ( auth.uid() in (select id from profiles where role = 'admin') ) 
    with check ( auth.uid() in (select id from profiles where role = 'admin') );
  end if;

  -- 评论策略
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Comments are viewable by everyone') then
    create policy "Comments are viewable by everyone" on comments for select using ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Authenticated users can create comments') then
    create policy "Authenticated users can create comments" on comments for insert to authenticated with check ( true );
  end if;
  if not exists (select 1 from pg_policies where tablename = 'comments' and policyname = 'Users can delete own comments') then
    create policy "Users can delete own comments" on comments for delete using ( auth.uid() = user_id );
  end if;
end $$;

-- 4. 创建触发器：注册后自动生成 user 资料
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
// ==========================================================
// 论坛系统完整后端服务逻辑 (包含 EmailJS 发信功能)
// 使用方式: 部署为 Supabase Edge Function 或在 Node 后端调用
// ==========================================================

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

// --- Supabase 核心初始化 ---
// 注意: 此 key 为前端安全 Public ANON Key，可在 Supabase API 设置中查看。
// 边缘函数中应使用 Service Role Key 执行高权限操作，示例这里使用 ANON Key 便于本地测试。
const supabaseUrl = 'https://cjyxleokhkpqkwziuy.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqeXhsZW9raGtwcWt3eml1eSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzM1MTU4NjUxLCJleHAiOjIwNTA3MzQ2NTF9.2WZ4P3Y2nPb_xoIe01V_-snWl3kY-Bi5tV2FqMl4bVc'
export const supabase = createClient(supabaseUrl, supabaseKey)

// --- 1. 辅助工具 ---
export async function getCurrentUser() {
    try {
        const { data: { user } } = await supabase.auth.getUser()
        return user
    } catch { return null }
}

// --- 2. 身份验证 (登录/注册) ---
export async function authUser(email: string, password: string, isRegister = false) {
    try {
        let res = isRegister 
            ? await supabase.auth.signUp({ email, password }) 
            : await supabase.auth.signInWithPassword({ email, password })
        
        if (res.error) throw new Error(res.error.message)
        // 强制校验邮箱
        if (res.data.user && !res.data.user.confirmed_at) {
             throw new Error("邮箱未验证，请先前往邮箱点击激活链接！")
        }
        return { success: true, data: res.data }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// --- 3. 论坛发布 (发帖) ---
export async function createPost(content: string) {
    try {
        const user = await getCurrentUser()
        if (!user) throw new Error("请先登录")
        const { error } = await supabase.from('posts').insert({ content, user_id: user.id })
        if (error) throw error
        return { success: true, msg: '发帖成功，等待管理员审核' }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// --- 4. 论坛读取 (列表与分页) ---
export async function getPosts(page = 1, pageSize = 20) {
    try {
        const from = (page - 1) * pageSize
        const to = from + pageSize - 1
        const { data, error, count } = await supabase
            .from('posts')
            .select('*, profiles(username)', { count: 'exact' })
            .eq('status', 'approved') // 只读取已公开的帖子
            .order('created_at', { ascending: false })
            .range(from, to)
        if (error) throw error
        return { success: true, data, count }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// --- 5. 论坛互动 (发评论) ---
export async function addComment(postId: number, content: string) {
    try {
        const user = await getCurrentUser()
        if (!user) throw new Error("请先登录")
        const { error } = await supabase.from('comments').insert({ post_id: postId, content, user_id: user.id })
        if (error) throw error
        return { success: true }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// --- 6. 管理员权限 (审核/封禁帖子) ---
export async function reviewPostByAdmin(postId: number, newStatus: 'approved' | 'banned') {
    try {
        const user = await getCurrentUser()
        if (!user) throw new Error("未登录")
        
        // 应用层双保险：检查是否是管理员 (最终依赖数据库 RLS 策略)
        const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
        if (!profile || profile.role !== 'admin') throw new Error("权限不足，仅限管理员操作")

        const { error } = await supabase.from('posts').update({ status: newStatus }).eq('id', postId)
        if (error) throw error
        return { success: true, msg: `帖子状态已变更为: ${newStatus}` }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// --- 7. 青年信箱功能 (结合 EmailJS 发送邮件到你的QQ) ---
// 此函数可放在 Supabase Edge Functions 中由前端触发调用
export async function sendYouthLetter(userEmail: string, messageContent: string) {
    try {
        if (!userEmail || !messageContent) {
            throw new Error("邮箱和内容不能为空")
        }

        // 获取 Supabase Secrets 中存储的 EmailJS 配置
        const publicKey = Deno.env.get("EMAILJS_PUBLIC_KEY")!
        const serviceId = Deno.env.get("EMAILJS_SERVICE_ID")!
        const templateId = Deno.env.get("EMAILJS_TEMPLATE_ID")!

        // 调用 EmailJS 官方 API
        const response = await fetch("https://api.emailjs.com/api/v1/email/send", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                service_id: serviceId,
                template_id: templateId,
                user_id: publicKey,
                template_params: {
                    user_email: userEmail,       // 对应 EmailJS 模板里的 {{user_email}}
                    message_content: messageContent // 对应 EmailJS 模板里的 {{message_content}}
                }
            })
        })

        if (response.ok) {
            return { success: true, message: "信件发送成功！" }
        } else {
            const errorText = await response.text()
            throw new Error(`EmailJS 发送失败: ${errorText}`)
        }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}
